export const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  ERROR:'connect_error',
  SEND_SOCKETID:'mobile-sendSocketId',
  RECIVE_USERS:'connectedUsers',
  GAME_START:'gameStart',
  GAME_STARTED:'isGameStarted',
  GAME_END: 'gameEnd',
  TURN_CHANGE:'assign-turn',
  INSUFFICIENT_PLAYERS:'mobile-insufficientPlayers',
  UPDATE_PLAYER: 'updatePlayer',
  REMOVE_PLAYER: 'removePlayer',
  KILLED_PLAYER: 'send-killedPlayer',
  GAME_RESET: 'gameReset',
  PLAYER_DATA: 'playerData',
  GAME_CREATED: 'isGameCreated',
  JOINED_BATTLE: 'mobile-joinBattle',
  GET_BATTLES: 'battles',
};

export const SOCKET_EMIT_EVENTS = {
  ATTACK: 'mobile-attack',
  SET_SELECTED_PLAYER: 'mobile-setSelectedPlayer',
  GAME_START: 'mobile-gameStart',
  GAME_RESET: 'mobile-gameReset',
  GAME_SELECTED: 'mobile-selectedBattle',
  CREATE_GAME: 'mobile-createGame',
  SIGN_IN: 'mobile-signIn',
  JOIN_BATTLE: 'mobile-joinBattle',
  GAME_CREATED: 'mobile-isGameCreated',
  GET_BATTLES: 'mobile-getBattles',
  GAME_STARTED: 'movile-isGameStarted',
};