import { Battle } from '../interfaces/Battle';

const mockBattles: Battle[] = [
  {
    'id': '1',
    'name': 'Forgotten Tavern',
    'description': 'In search of Angelo, a dark secret lurks in the shadows of the tavern.',
    'enemies': ['boss_id', 'boos_id'],
    'suggested_level': 7,
    'drop_item_level': 7,
    'gold': 300,
    'exp': 1500,
    'battle_background': 'tabern.webp',
    'battle_animations': ['player.gif', 'boss.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '2',
    'name': 'The Profane Ritual',
    'description': 'A coven of warlocks has summoned horrors from beyond the veil. Stop them before it’s too late.',
    'enemies': ['warlock_id', 'demon_id'],
    'suggested_level': 10,
    'drop_item_level': 10,
    'gold': 500,
    'exp': 2500,
    'battle_background': 'ritual.webp',
    'battle_animations': ['player.gif', 'warlock.gif', 'demon.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '3',
    'name': 'Forgotten Tavern',
    'description': 'In search of Angelo, a dark secret lurks in the shadows of the tavern.',
    'enemies': ['boss_id', 'boos_id'],
    'suggested_level': 7,
    'drop_item_level': 7,
    'gold': 300,
    'exp': 1500,
    'battle_background': 'tabern.webp',
    'battle_animations': ['player.gif', 'boss.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '4',
    'name': 'The Profane Ritual',
    'description': 'A coven of warlocks has summoned horrors from beyond the veil. Stop them before it’s too late.',
    'enemies': ['warlock_id', 'demon_id'],
    'suggested_level': 10,
    'drop_item_level': 10,
    'gold': 500,
    'exp': 2500,
    'battle_background': 'ritual.webp',
    'battle_animations': ['player.gif', 'warlock.gif', 'demon.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '5',
    'name': 'Forgotten Tavern',
    'description': 'In search of Angelo, a dark secret lurks in the shadows of the tavern.',
    'enemies': ['boss_id', 'boos_id'],
    'suggested_level': 7,
    'drop_item_level': 7,
    'gold': 300,
    'exp': 1500,
    'battle_background': 'tabern.webp',
    'battle_animations': ['player.gif', 'boss.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '6',
    'name': 'The Profane Ritual',
    'description': 'A coven of warlocks has summoned horrors from beyond the veil. Stop them before it’s too late.',
    'enemies': ['warlock_id', 'demon_id'],
    'suggested_level': 10,
    'drop_item_level': 10,
    'gold': 500,
    'exp': 2500,
    'battle_background': 'ritual.webp',
    'battle_animations': ['player.gif', 'warlock.gif', 'demon.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '7',
    'name': 'Forgotten Tavern',
    'description': 'In search of Angelo, a dark secret lurks in the shadows of the tavern.',
    'enemies': ['boss_id', 'boos_id'],
    'suggested_level': 7,
    'drop_item_level': 7,
    'gold': 300,
    'exp': 1500,
    'battle_background': 'tabern.webp',
    'battle_animations': ['player.gif', 'boss.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '8',
    'name': 'The Profane Ritual',
    'description': 'A coven of warlocks has summoned horrors from beyond the veil. Stop them before it’s too late.',
    'enemies': ['warlock_id', 'demon_id'],
    'suggested_level': 10,
    'drop_item_level': 10,
    'gold': 500,
    'exp': 2500,
    'battle_background': 'ritual.webp',
    'battle_animations': ['player.gif', 'warlock.gif', 'demon.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '9',
    'name': 'Forgotten Tavern',
    'description': 'In search of Angelo, a dark secret lurks in the shadows of the tavern.',
    'enemies': ['boss_id', 'boos_id'],
    'suggested_level': 7,
    'drop_item_level': 7,
    'gold': 300,
    'exp': 1500,
    'battle_background': 'tabern.webp',
    'battle_animations': ['player.gif', 'boss.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '10',
    'name': 'The Profane Ritual',
    'description': 'A coven of warlocks has summoned horrors from beyond the veil. Stop them before it’s too late.',
    'enemies': ['warlock_id', 'demon_id'],
    'suggested_level': 10,
    'drop_item_level': 10,
    'gold': 500,
    'exp': 2500,
    'battle_background': 'ritual.webp',
    'battle_animations': ['player.gif', 'warlock.gif', 'demon.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '11',
    'name': 'Forgotten Tavern',
    'description': 'In search of Angelo, a dark secret lurks in the shadows of the tavern.',
    'enemies': ['boss_id', 'boos_id'],
    'suggested_level': 7,
    'drop_item_level': 7,
    'gold': 300,
    'exp': 1500,
    'battle_background': 'tabern.webp',
    'battle_animations': ['player.gif', 'boss.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  },
  {
    'id': '12',
    'name': 'The Profane Ritual',
    'description': 'A coven of warlocks has summoned horrors from beyond the veil. Stop them before it’s too late.',
    'enemies': ['warlock_id', 'demon_id'],
    'suggested_level': 10,
    'drop_item_level': 10,
    'gold': 500,
    'exp': 2500,
    'battle_background': 'ritual.webp',
    'battle_animations': ['player.gif', 'warlock.gif', 'demon.gif'],
    'end_of_battle_background': ['victory.webp', 'defeat.webp']
  }];

export default mockBattles;