name: Deploy Kaotika Battle Mobile (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.MOBILE_ENV_FILE }}" > .env

      - name: Pull latest changes
        run: git pull origin main

      - name: Build and restart Docker container
        run: |
          cd $GITHUB_WORKSPACE
          docker rm -f kaotika-battle-mobile || true
          docker compose -f docker-compose.yml build web
          docker compose -f docker-compose.yml up -d web

      - name: Clean up
        run: echo "Deployment complete."
