name: Deploy Kaotika Battle Mobile (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js  # Añadimos esta acción para tener node instalado
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Cambia la versión si usas otra

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.MOBILE_ENV_FILE }}" > .env

      - name: Pull latest changes
        run: git pull origin main

      - name: Build and restart Docker container
        run: |
          cd $GITHUB_WORKSPACE
          docker rm -f kaotika-battle-mobile || true
          docker compose -f docker-compose.yml build mobile
          docker compose -f docker-compose.yml up -d mobile

      - name: Clean up
        run: echo "Deployment complete."
