name: Deploy Kaotika Battle Mobile

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Actualizar código
        run: git pull origin main
      - name: Instalar dependencias
        run: npm install
      - name: Construir React
        run: npm run build
      - name: Reiniciar apps en PM2
        run: pm2 restart all
