name: Deploy Kaotika Battle Mobile

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Kaotika Battle Mobile
        run: |
          ssh -o StrictHostKeyChecking=no user@10.50.0.50 << 'EOF'
          cd /home/daw2/Documentos/ReactJS-Projects/kaotika-battle-mobile
          git pull origin main
          npm install
          npm run build
          pm2 restart kaotika-battle-mobile
          EOF
